### ISSUE TITLE
add basename to plot_isoDist.R

### ISSUE THREAD

**Issue by Jeltje** [FlorianThibord/OptimiR#2]
`out_basename <- paste(res_directory, gsub(".annot", "", basename(isomiR_table_path)),sep="/")`

allows the user to run the script with an input path instead of a filename.

Details:

```
Rscript Optimir-1.0/optimir/R_plot/plot_isoDist.R optimir_BFX67/Optimir_group_results/isomiRs_dist.annot
optimir_BFX67/Optimir_group_results/graphsError in plot.new() :
  could not open file 'optimir_BFX67/Optimir_group_results/graphs/optimir_BFX67/Optimir_group_results/isomiRs_dist_TOTAL.png'
```

**Comment by FlorianThibord** [comment]
Hi @Jeltje 
Thank you very much for your input! This error has been corrected.
FYI, plot_isoDist.R will be updated soon in order to generate barplots instead of pie charts
