### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by JFsanchezherrero** [FlorianThibord/OptimiR#3]
Hi there,

I guess there is an error when installing optimir using conda

I have found the following error:

```
  File "/lib/python3.6/site-packages/optimir/libs/library_preparation.py", line 209, in make_OptimiR_dict
    print("Hairpin allready present : {} in {}".format(hairpin_name, new_hairpin_dict))
NameError: name 'new_hairpin_dict' is not defined

```

I guess the commit 7598fadff682ce693b4ba92a3a476b524367260d fixed it but as a new release was not done, the conda recipe is not up to date. 

New release of the code should be done and conda recipe should be modified to include new version:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/optimir/meta.yaml

I have included OptimiR in my new pipeline XICRA (https://github.com/HCGB-IGTP/XICRA) which is about to be released and it would be great to have OptimiR fix and working soon.

Thank you very much

**Comment by FlorianThibord** [comment]
Hi @JFsanchezherrero ,
Thanks for pointing this out! Indeed I forgot to make a new release after correcting this error... I will fix it asap, update the conda recipe and let you know.
PS: XICRA looks very interesting, congrats on this work!

**Comment by JFsanchezherrero** [comment]
Hi there! Thanks for the quick response! 
Also, thanks for the compliment on XICRA. I would send you the paper once published. I guess next week(s).
I am looking forward to having OptimiR working.  Let me know when you are ready.
Best regards

**Comment by FlorianThibord** [comment]
Hi
I just created the new release and updated the bioconda recipe. Once the pull request is accepted I will close this issue.

Best

**Comment by JFsanchezherrero** [comment]
Thanks Florian!

Best regards

**Comment by FlorianThibord** [comment]
Hi @JFsanchezherrero , 
just a quick confirmation: the PR has been accepted, optimir should now run smoothly via conda.
