### ISSUE TITLE
Bowtie2 has changed sequence of command line options

### ISSUE THREAD

**Issue by tillea** [FlorianThibord/OptimiR#4]
Hi,
the CI test in Debian failed since bowtie2 was upgraded to version 2.4.5 as it was reported in a [bug report](https://bugs.debian.org/1006657).  I found a simple [patch](https://salsa.debian.org/med-team/optimir/-/blob/master/debian/patches/fix_sequence_of_options_in_bowtie2.patch) where I only changed the position of the ```-q``` option.  Feel free to either apply this patch to OptimiR or contact bowtie2 authors to relax the sequence of command line options.
Kind regards, Andreas.

**Comment by FlorianThibord** [comment]
Thanks for letting me know and finding a patch @tillea !
I'll make the change in the github repo and make a new release shortly.

**Comment by tillea** [comment]
Am Thu, Mar 10, 2022 at 12:37:26PM -0800 schrieb FlorianThibord:
> Thanks for letting me know and finding a patch @tillea !
Thanks a lot for the quick response, Andreas.
